Welcome windows graphics - sign in & sign up
B-E-D-A/Text-Editor-with-AI pull request #1
Opened 2024-03-08 17:09 UTC by B-E-D-A

2024-03-09 23:02 UTC, OlesiaSub requested changes
если что -- необязательно исправлять абсолютно все, часть комментариев просто for your information :)

2024-03-09 23:02 UTC, OlesiaSub commented on README.md
> +![#e0850c](https://placehold.co/15x15/e0850c/e0850c.png) `#e0850c`
можешь схематично написать, что тут будет? (и зачем тут эти цвета?)
еще было бы здорово, если бы вы даже в процессе работы вставляли скрины с такущим состоянием либо в само ридми, либо прикрепляли к пр-у

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/FirstViewController.java
> +package org.demo.texteditorwithai;
я бы сделала базовым пакетом org.hse.texteditorwithai и разделила бы файлы на более специфичные, условно sign in, utils и тд

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/Main.java
> +    public static final int defaultHeight = 400;
для настроек внешнего вида лучше создать отдельный файлик. в простом варианте -- java class with static fields
но лучше такие настройки задавать через что-нибудь типа properties file (https://www.baeldung.com/java-properties)

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/FirstViewController.java
> +public class FirstViewController implements Initializable {
добавь, пожалуйста, комментарии к классам. можно прямо небольшие, просто чтобы было понятно, за что класс отвечает

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/FirstViewController.java
> +    protected void loadScene(Stage stage, String fxmlView) throws IOException {
style nitpick --  новая строка перед методом очень просится 🙏

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/FirstViewController.java
> +            System.err.println(e.getMessage());
это вообще не обязательно, но красивее было бы выводить ошибки логгерами (https://www.baeldung.com/java-logging-intro)
не настаиваю на их добавлении, скорее просто держу в курсе
но к исключению я бы в любом случае добавила что-нибудь типа "Scene configuration file not found. " + e.getMessage()

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/MainWindowController.java
> +public class MainWindowController {
какая у него цель существования?

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +                passwordVisible = !passwordVisible;
это кажется копипаста того, что выше, просто с инвертированными переменными. так что можно вынести в функцию

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +        });
в целом тоже можно вынести в функицю

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +            System.err.println(e.getMessage());
same here, хочется чуть более детального error message

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +    protected boolean checkIfEmpty() {
`isLoginValid` или что-то подобное более понятно описывало бы функциональность метода

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +    protected void signInButtonClicked() {
general question, @FXML annotation здесь просто потому везде юзается javafx?
и почему многие методы и поля `protected` instead of `private`?

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +    public void enter(Stage stage) {
кажется может быть private

еще общее замечание, обычно принято public методы держать в верхней части класса, потом protected, потом private methods / inner classes, etc

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/java/org/demo/texteditorwithai/SignUpController.java
> +    protected void loadSuccessScene(Stage stage, String fxmlView) throws IOException {
выбери какую-нибудь одну стратегию хендлинга исключений, сейчас часть методов их кидает и в итоге пробрасывает через всё, а часть методов ловит. 

не стоит оставлять их в `throws` секции, если никакой из методов, находящихся выше в иерархии вызовов, не ловит их. так что в данном случае можно исключения из этого метода поймать в `signUpButtonClicked`, а можно и в самом этом методе.

2024-03-09 23:02 UTC, OlesiaSub commented on src/main/resources/org/demo/texteditorwithai/closed-eye.png
общий комментарий к ресурсам -- не стоит кидать все в одну кучу. лучше раздели все ресурсы на папки типа assets (с картинками), views (fxml), css, configs и тп

2024-03-10 02:53 UTC, B-E-D-A commented on src/main/java/org/demo/texteditorwithai/SignInController.java
> +    protected void signInButtonClicked() {
@FXML стоит, потому что поля или методы используются в javafx, да. Методы и поля не `private`, т.к. иначе их не видит файл `.fxml`

2024-04-10 02:32 UTC, merged